import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  copyFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function log(msg) {
  console.log(`  ${msg}`);
}

function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function stringifyEnv(vars, headerLines = []) {
  const lines = [...headerLines];
  for (const [key, value] of Object.entries(vars)) {
    lines.push(`${key}=${value}`);
  }
  return `${lines.join("\n")}\n`;
}

function ensureCopy(srcRel, destRel) {
  const src = join(root, srcRel);
  const dest = join(root, destRel);
  if (!existsSync(src)) {
    log(`skip ${destRel} (missing template ${srcRel})`);
    return { created: false, path: dest };
  }
  if (existsSync(dest)) {
    log(`keep ${destRel} (already exists)`);
    return { created: false, path: dest };
  }
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(src, dest);
  log(`create ${destRel}`);
  return { created: true, path: dest };
}

function isPlaceholderSecret(value) {
  if (!value) return true;
  return (
    value.includes("replace-with") ||
    value.includes("change-me") ||
    value.length < 32
  );
}

function isPlaceholderDb(value) {
  if (!value) return true;
  return (
    value.includes("user:pass@localhost") ||
    value.includes("postgres://user:pass")
  );
}

console.log("\nDocket setup\n");

// 1. Env files from templates
ensureCopy(".env.example", ".env");
ensureCopy("apps/api/.dev.vars.example", "apps/api/.dev.vars");
ensureCopy("apps/web/.env.example", "apps/web/.env");

// 2. Sync secrets between root .env and api .dev.vars
const envPath = join(root, ".env");
const devVarsPath = join(root, "apps/api/.dev.vars");
const env = existsSync(envPath) ? parseEnv(readFileSync(envPath, "utf8")) : {};
const devVars = existsSync(devVarsPath)
  ? parseEnv(readFileSync(devVarsPath, "utf8"))
  : {};

let secret =
  (!isPlaceholderSecret(env.BETTER_AUTH_SECRET) && env.BETTER_AUTH_SECRET) ||
  (!isPlaceholderSecret(devVars.BETTER_AUTH_SECRET) &&
    devVars.BETTER_AUTH_SECRET) ||
  randomBytes(32).toString("hex");

if (
  isPlaceholderSecret(env.BETTER_AUTH_SECRET) ||
  isPlaceholderSecret(devVars.BETTER_AUTH_SECRET)
) {
  log("generate BETTER_AUTH_SECRET");
}

const databaseUrl =
  (!isPlaceholderDb(env.DATABASE_URL) && env.DATABASE_URL) ||
  (!isPlaceholderDb(devVars.DATABASE_URL) && devVars.DATABASE_URL) ||
  env.DATABASE_URL ||
  devVars.DATABASE_URL ||
  "postgres://user:pass@localhost:5432/docket";

env.BETTER_AUTH_SECRET = secret;
env.DATABASE_URL = databaseUrl;
env.NODE_ENV = env.NODE_ENV || "development";
env.VITE_API_URL = env.VITE_API_URL || "http://localhost:8787";
env.BETTER_AUTH_URL = env.BETTER_AUTH_URL || "http://localhost:8787";
env.COOKIE_DOMAIN = env.COOKIE_DOMAIN || "localhost";
env.APP_URL = env.APP_URL || "http://localhost:5173";

devVars.BETTER_AUTH_SECRET = secret;
devVars.DATABASE_URL = databaseUrl;

writeFileSync(
  envPath,
  stringifyEnv(env, [
    "# Generated/updated by npm run setup — do not commit",
    "",
  ]),
);
writeFileSync(
  devVarsPath,
  stringifyEnv(devVars, [
    "# Wrangler local secrets — do not commit",
    "",
  ]),
);
log("sync .env ↔ apps/api/.dev.vars");

const webEnvPath = join(root, "apps/web/.env");
writeFileSync(
  webEnvPath,
  stringifyEnv(
    { VITE_API_URL: env.VITE_API_URL || "http://localhost:8787" },
    ["# Generated by npm run setup — do not commit", ""],
  ),
);
log("write apps/web/.env");

// 3. Agent rules mirror
const sync = spawnSync(process.execPath, [join(root, "scripts/rules-sync.mjs")], {
  cwd: root,
  stdio: "inherit",
});
if (sync.status !== 0) {
  console.error("\nrules:sync failed");
  process.exit(sync.status ?? 1);
}

// 4. Remind about install / migrate
const needsDb = isPlaceholderDb(databaseUrl);
console.log("\nDone.\n");
console.log("Next:");
if (needsDb) {
  console.log("  1. Set DATABASE_URL in .env (Neon connection string)");
  console.log("  2. Re-run: npm run setup   # syncs into apps/api/.dev.vars");
  console.log("  3. npm install");
  console.log("  4. npm run db:migrate && npm run db:seed");
  console.log("  5. npm run dev");
} else {
  console.log("  npm install");
  console.log("  npm run db:migrate && npm run db:seed");
  console.log("  npm run dev");
}
console.log("");
